name: Scrape

on:
  schedule:
    - cron: '5 15 * * *'
  workflow_dispatch:

jobs:
  selenium-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager reportlab

      - name: Run Selenium script in Headless
        run: |
          python bot_scrape.py

      - name: Commit PDF to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@github.com"
          git add halal_menus.pdf
          git commit -m "Update PDF $(date -u)" || echo "No changes to commit"
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
