name: Scrape

on:
  schedule:
    - cron: '5 15 * * *'  # 11:05 AM EDT / 15:05 UTC
    - cron: '5 21 * * *'  # 5:05 PM EDT / 21:05 UTC
  workflow_dispatch:

jobs:
  selenium-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager reportlab

      - name: Run Selenium script in Headless
        env:
          CHROME_BIN: /usr/bin/google-chrome
        run: |
          python src/bot_scrape.py

      - name: Run Muslim Calendar Script
        run: |
          python src/get_muslim_calendar.py

      - name: Commit PDF to repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@github.com"
          git add outputs/halal_menus.pdf
          git add outputs/halal_menus.txt
          git add outputs/muslim_calendar.pdf
          git commit -m "Scraped NetNutrition & Calendar $(date -u)" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD:main